[target.aarch64-unknown-linux-gnu]
pre-build = "apt install sqlite3"
[target.arm-unknown-linux-gnu]
pre-build = "apt install sqlite3"
[target.armv7-unknown-linux-gnu]
pre-build = "apt install sqlite3"
[target.x86_64-unknown-linux-gnu]
pre-build = "apt install sqlite3"